SELECT * FROM jan7batch.cric_players;

create table cric_players(sl_no int, player_name varchar(50), position int, ratings int, country varchar(50), ipl_team varchar(50), best_series varchar(50), father varchar(50), mother varchar(50), brother varchar(50), city varchar(50), area varchar(50), pincode bigint, state varchar(50), Test_debut varchar(50));


INSERT into cric_players values(1, 'Marnus Labuschagne', 101, 929, 'India', 'CSK', 'New Zealand tour of Pakistan, 2022-23', 'A. K. Hangal', 'Patience Cooper', 'Allu Arjun', 'Mumbai', 'YESHWANTHAPUR', 110000, 'KA', 'India v Sri Lanka, 2023');
INSERT into cric_players values(2, 'Steven Smith', 102, 828, 'Afghanistan', 'DC', 'Sri Lanka tour of India, 2023', 'Aadhi', 'Fatma Begum', 'Master Anand', 'Delhi', 'SANJAYNAGAR', 110001, 'Kar', 'New Zealand vs Pakistan');
INSERT into cric_players values(3, 'Babar Azam', 103, 862, 'Ireland', 'Punjab Kings', 'Ireland tour of Zimbabwe, 2023', 'Aadi Pudipeddi', 'Mahesh Babu', 'Mahesh', 'Bangalore', 'MALLESHWARAM', 110002, 'Karnataka', 'Pakistan v New Zealand');
INSERT into cric_players values(4, 'Travis Head', 104, 841, 'Pak', 'KKR', 'New Zealand tour of India, 2023', 'Aamir Khan', 'Sadhana Bose', 'Ramesh Babu', 'Hyderabad', 'MAHALAKSHMIPURA', 110003, 'AP', 'Zimbabwe v Ireland');
INSERT into cric_players values(5, 'Joe Root', 105, 826, 'Australia', 'MI', 'England tour of South Africa, 2023', 'Aashish', 'Nalini Jaywant', 'Subir Banerjee', 'Ahmedabad', 'GAYATHRINAGAR', 110004, 'Andra', 'Adelaide Strikers vs Melbourne Stars');
INSERT into cric_players values(6, 'Kane Williamson', 106, 810, 'Srilanka', 'RCB', 'West Indies tour of Zimbabwe, 2023', 'Aashish Naik', 'Sulochana Latkar', 'Vishesh Bansal', 'Kolkata', 'RAJAJINAGAR', 110005, 'AndraPradesh', 'Ireland vs Zimbabwe');
INSERT into cric_players values(7, 'Rishabh Pant', 107, 797, 'Bangla', 'RR', 'Australia tour of India, 2023', 'Abbas', 'Veena', 'Yagya Bhasin', 'Surat', 'SRIRAMAMANDIRA', 110006, 'Telangana', 'Sydney Thunder vs Perth Scorchers');
INSERT into cric_players values(8, 'Usman Khawaja', 108, 770, 'Uk', 'SRH', 'England tour of New Zealand, 2023', 'Abhay Deol', 'Meena Shorey', 'Saumya Daan', 'Vadodara', 'GANDHINAGAR', 110007, 'TL', 'Adelaide Strikers vs Brisbane Heat');
INSERT into cric_players values(9, 'Dimuth Karunaratne', 109, 748, 'England', 'Deccan Gladiators', 'West Indies tour of South Africa, 2023', 'Abhay', 'Swaran Lata', 'Swaran', 'Pune', 'CHICKPET', 110008, 'Kerala', 'Melbourne Renegades vs Melbourne Stars');
INSERT into cric_players values(10, 'Rohit Sharma', 110, 732, 'British', 'London Spririt', 'England tour of Bangladesh, 2023', 'Abhijeeth', 'Leela Desai', 'Parzaan Dastur', 'Lucknow', 'CHAMARAJPET', 110009, 'KL', 'Hobart Hurricanes vs Sydney Thunder');
INSERT into cric_players values(11, 'Daryl Mitchell', 111, 712, 'EI', 'Birmingham Phoenix', 'Sri Lanka tour New Zealand, 2023', 'Abhishek', 'Mumtaz Shanti', 'Shanth', 'Indore', 'BINNYPET', 110010, 'Arunachal Pradesh', 'Sydney Sixers vs Perth Scorchers');
INSERT into cric_players values(12, 'Litton Das', 113, 702, 'WI', 'Welsh Fire', 'Netherlands tour of South Africa, 2023', 'Abhishek Banerjee', 'Nargis', 'Bobby Deol', 'Thane', 'GOVINDARAJ NAGAR', 110011, 'JK', 'Joburg Super Kings vs Durban Super Giants');
INSERT into cric_players values(13, 'Jonny Bairstow', 114, 697, 'WEST I', 'Oval Invincibles', 'New Zealand tour of Pakistan, 2023', 'Abhimanyu Dassani', 'Suraiya', 'Dassani', 'Bhopal', 'CHANDRA LAYOUT', 110012, 'Ladakh', 'Pretoria Capitals vs Sunrisers Eastern Cape');
INSERT into cric_players values(14, 'David Warner', 115, 680, 'WEST INDIES', 'Pune Devils', 'Ireland tour of England Only Test, 2023', 'Abhimanyu Singh', 'Noor Jehan', 'Singh', 'Visakhapatnam', 'JAGAJEEVAN RAMNAGAR', 110013, 'Pondicheerry', 'Durban Super Giants vs Paarl Royals');
INSERT into cric_players values(15, 'Virat Kohli', 116, 676, 'SA', 'Team Abu Dhabi', 'The Ashes, 2023', 'Abijeet Duddala', 'Abir Chatterjee', 'Achyuth Kumar', 'Patna', 'BASAVANAGUDI', 110014, 'TN', 'Fortune Barishal vs Chattogram Challengers');
INSERT into cric_players values(16, 'Dinesh Chandimal', 117, 673, 'South Africa', 'Bangla Tigers', 'New Zealand tour of England, 2023', 'Adil Hussain', 'Kamala Kotnis', 'Adil', 'Ghaziabad', 'HANUMANTH NAGAR', 110015, 'TamilNadu', 'Khulna Tigers vs Rangpur Riders');
INSERT into cric_players values(17, 'Tom Blundell', 118, 671, 'Africa', 'Qalandars', 'Ireland tour of England ODI Series, 2023', 'Aditya Babu', 'Rehana', 'Meena Kumari', 'Ludhiana', 'PADMANABHA NAGAR', 110016, 'MH', 'Comilla Victorians vs Fortune Barishal');
INSERT into cric_players values(18, 'Shreyas Iyer', 119, 666, 'Zimbabwe', 'Belfast Titans', 'Bangladesh tour of New Zealand, 2022', 'Aditya Seal', 'Shashikala', 'Sanjay Dutt', 'Nashik', 'JAYANAGAR', 110017, 'Maharastra', 'Chattogram Challengers vs Dhaka Dominators');
INSERT into cric_players values(19, 'Tom Latham', 120, 654, 'NZ', 'Delhi bulls', 'India tour of South Africa, 2021-22', 'Ajay', 'Madhubala', 'Uma Anand', 'Meerut', 'HOMBEGOWDA NAGAR', 110018, 'DravidaNadu', 'Dubai Capitals vs Abu Dhabi Knight Riders');
INSERT into cric_players values(20, 'Angelo Mathews', 121, 653, 'NewZealand', 'Manchester Originals', 'Ireland tour of USA, 2021', 'Ajmal Ameer', 'Nigar Sultana', 'Kamal Haasan', 'Varanasi', 'MADIWALA', 110019, 'Karunadu', 'MI Emirates vs Sharjah Warriors');
INSERT into cric_players values(21, 'Devon Conway', 122, 646, 'Malaysia', 'Northern Superchargers', 'West Indies tour of Pakistan, 2021-22', 'Amit Sadh', 'Kamini Kaushal', 'Nandamuri Harikrishna', 'Srinagar', 'Hanumanagar', 110020, 'Delhi', 'Abu Dhabi Knight Riders vs Gulf Giants');
INSERT into cric_players values(22, 'Cheteshwar Pujara', 123, 642, 'Nepal', 'Desert Riders', 'The Ashes, 2021-22', 'Afghanistan tour of Australia Only Test, 2021', 'Ajinkya Dev', 'Nutan', 'Aurangabad', 'KORAMANGALA', 110021, 'Up', 'Canterbury vs Northern Knights');
INSERT into cric_players values(23, 'Temba Bavuma', 124, 640, 'Germany', 'Flying Oryx', 'Netherlands tour of South Africa, 2021', 'Aju Varghese', 'Geeta Bali', 'Vinayak Joshi', 'Amritsar', 'SHANTHINAGAR', 110022, 'MP', 'Auckland vs Central Districts');
INSERT into cric_players values(24, 'Mushfiqur Rahim', 125, 639, 'Namibia', 'Falcon Hunters', 'Pakistan tour of Bangladesh, 2021', 'Amitabh Bachchan', 'Vyjayanthimala', 'Tanmay Jahagirdar', 'Navi Mumbai', 'JEEVANBHEEMA NAGAR', 110023, 'UttarPradesh', '');
INSERT into cric_players values(25, 'Kraigg Brathwaite', 126, 637, 'Denmark', 'Khulna Tigers', 'ICC Mens T20 World Cup Africa Qualifier 2021', 'Auditya', 'Sandhya', 'Mohan Kanda', 'Allahabad', 'BHARATHINAGAR', 110024, 'MadyaPradesh', 'Otago vs Wellington');
INSERT into cric_players values(26, 'Ben Stokes', 127, 633, 'Singapore', 'Rajshahi Royals', 'New Zealand tour of India, 2021', 'Ajay Devgan', 'Nadira', 'Rishi Kapoor', 'Faridabad', 'SARVAGNA NAGAR', 110025, 'Bihar', 'Arunachal Pradesh vs Sikkim');
INSERT into cric_players values(27, 'Mayank Agarwal', 128, 631, 'papua New Guinea', 'Dhaka Platoon', 'West Indies tour of Sri Lanka, 2021 ', 'Ajit Khan', 'Ameeta', 'Shashi Kapoor', 'Ranchi', 'BANASWADI', 110026, 'Chandigarh', 'Meghalaya vs Manipur');
INSERT into cric_players values(28, 'Alex Carey', 129, 628, 'New Guinea', 'Rangpur Rangers', 'Gibraltar tour of Malta, 2021', 'B. C. Patil', 'Sadhana', 'Vinoth Kishan', 'Jabalpur', 'SHIVAJINAGAR', 110027, 'Chattisgarh', 'Mumbai vs Assam');
INSERT into cric_players values(29, 'Ollie Pope', 130, 621, 'Kuwait', 'Cumilla Warrior', 'ICC Mens T20 World Cup 2021', 'B. R. Panthulu', 'Balakrishna', 'P. Sai Kumar', 'Coimbatore', 'Ranaganakunte', 110028, 'Odisha', 'Baroda vs Bengal');
INSERT into cric_players values(30, 'Imam-ul-Haq', 131, 614, 'Vanuatu', 'Chattogram Challengers', 'ICC Mens T20 World Cup Europe Qualifier 2021', 'Balakrishna Nandamuri', 'Anjali Devi', 'Kavish Majumdar', 'Vijayawada', 'Uneshoura', 110029, 'Punjab', 'Rajasthan vs Karnataka');
INSERT into cric_players values(31, 'Mohammad Rizwan', 132, 604, 'Jersy', 'Sylhet Thunder', 'England tour of Pakistan, 2021', 'Dhanush', 'Mala Sinha', 'Master Manjunath', 'Jodhpur', 'Esha nagar', 110030, 'Rajastan', 'Jharkhand vs Chhattisgarh');
INSERT into cric_players values(32, 'Sean Williams', 133, 603, 'Oman', 'Trent Rockets', 'UAE Summer T20 Bash 2021', 'Dhruva Sarja', 'Saroja Devi', 'Mikhail Gandhi', 'Madurai', 'JAYAMAHAL', 110031, 'UttarKhand', 'Kerala vs Services');
INSERT into cric_players values(33, 'Dean Elgar', 134, 596, 'Ukraine', 'Southern Brave', 'New Zealand tour of Pakistan, 2021', 'Dharmendra', 'Neil Nitin Mukesh', 'Aditya Narayan', 'Raipur', 'HEBBAL', 110032, 'UK', 'Bihar vs Mizoram');
INSERT into cric_players values(34, 'Azhar Ali', 135, 589, 'Fijji', 'Dublin Chiefs', 'Zimbabwe tour of Scotland, 2021', 'Emraan Hashmi', 'Tanuja Samarth', 'Ganapathi S. Poduval', 'Chandigarh', 'KADUGONDANA HALLI', 110033, 'Manipur', 'Nagaland vs Haryana');
INSERT into cric_players values(35, 'Colin de Grandhomme', 136, 581, 'Russia', 'Glasgow Giants', 'United States v Papua New Guinea in Oman, 2021', 'Aayegi', 'Mumtaz', 'Akash Puri', 'Guwahati', 'BOMMANAHALLI', 110034, 'Assam', 'Maharashtra vs Tamil Nadu');
INSERT into cric_players values(36, 'Henry Nicholls', 137, 580, 'USA', 'Jozi Stars', 'Nepal v Papua New Guinea in Oman, 2021', 'Dingri Nagaraj', 'Sharmila Tagore', 'Sree Raam', 'Solapur', 'BYATARAYANA PURA', 110035, 'Nagaland', 'Tripura vs Railways');
INSERT into cric_players values(37, 'Abid Ali', 138, 578, 'Italy', 'Durban Heat', 'South Africa tour of Sri Lanka, 2021', 'Dino Morea', 'Moushumi Chatterjee', 'Vijay Raghavendra', 'Dharwad', 'Xworkz layout', 110036, 'Meghalaya', 'Hyderabad vs Saurashtra');
INSERT into cric_players values(38, 'Ravindra Jadeja', 139, 577, 'Iran', 'Durban', 'New Zealand tour of Bangladesh, 2021 ', 'Faisal Khan', 'Hema Malini', 'Chatterjee', 'Bareilly', 'DASARAHALLI', 110037, 'Haryana', 'Madhya Pradesh vs Gujarat');
INSERT into cric_players values(39, 'Cameron Green', 140, 570, 'Sothee', 'Dublin', 'Zimbabwe tour of Ireland, 2021', 'Gippy Grewal', 'Jaya Bachchan', 'Shafiq Syed','Mysore', 'MAHADEVAPURA', 110038, 'Gujrat', 'Vidarbha vs Chandigarh');
INSERT into cric_players values(40, 'Dhananjaya de Silva', 141, 521, 'UAE', 'Chiefs', 'Australia tour of Bangladesh, 2021', 'Guruprasad', 'Raakhee', 'Udayaraj', 'Moradabad', 'RAJARAJESHWARINAGAR', 110039, 'A&N Islands', 'Andhra vs Delhi');
INSERT into cric_players values(41, 'Shakib Al Hasan', 142, 534, 'Uganda', ' Brave', 'Pakistan tour of West Indies, 2021', 'Hardy Sandhu', 'Dimple Kapadia', 'Ananda Vardhan', 'Aligarh', 'Tumlur', 110040, 'Lakshadweep', 'Jammu and Kashmir vs Punjab');
INSERT into cric_players values(42, 'Ajinkya Rahane', 143, 523, 'Hongkong', 'Southern ', 'India tour of England, 2021', 'Harisree Ashokan', 'Lakshmi', 'Madhav Vaze', 'Gurgaon', 'Tumkur', 110041, 'Goa', 'United Arab Emirates vs Scotland');
INSERT into cric_players values(43, 'Tamim Iqbal', 144, 528, 'Kebya', 'Trent', 'India tour of Sri Lanka, 2021', 'Harman Baweja', 'J. P. Chandrababu', 'Sudheesh',  'Jalandhar', 'Tumakuru', 110042, 'Arunachal Pradesh', 'Australia vs Bangladesh');
INSERT into cric_players values(44, 'Keegan Petersen', 145, 517, 'Kenya', 'Rockets', 'South Africa tour of Ireland, 2021 ', 'Jagapati Babu', 'Deepti Naval', 'Karan Trivedi', 'Bhubaneswar', 'Mahalakshi layout', 110043, 'Manipura', 'Manipur vs AP');
INSERT into cric_players values(45, 'Harry Brook', 146, 516, 'Scotland', ' Warrior', 'Australia tour of West Indies, 2021', 'Jaggesh', 'Jaya Prada', 'Sunil Raoh', 'Salem', 'Kuvempu nagar', 110044, 'WB', 'AP vs KA');
INSERT into cric_players values(46, 'Abdullah Shafique', 147, 513, 'Thailand', 'Cumilla ', 'Pakistan tour of England, 2021', 'Jai Akash', 'Madhavi', 'Akash Puri', 'Thiruvananthapuram', 'Raj kumar road', 110045, 'West Benngal', 'Karnataka vs Kerala');
INSERT into cric_players values(47, 'Jermaine Blackwood', 148, 510, 'Netherlands', ' Thunder', 'Bangladesh tour of Zimbabwe, 2021', 'Kona Venkat', 'Indrajith Sukumaran', 'Mohan Kanda', 'Saharanpur', 'Bashyam Circle', 110046, 'South India', 'Ladakh vs Chennai');
INSERT into cric_players values(48, 'Niroshan Dickwella', 112, 507, 'Bermuda', 'Sylhet ', 'Sri Lanka tour of England, 2021', 'Kanha Mishra', 'Madhuri Dixit', 'Tanmay Jahagirdar', 'Gorakhpur', 'Viajanahar', 110047, 'North India', 'RajajiNagar vs BTM');
INSERT into cric_players values(49, 'Kyle Verreynne', 149, 506, 'Canada', 'Rangpur', 'ICC World Test Championship Final 2021', 'Kuthiravattam Pappu', 'Pooja Bhatt',  'Saumya Daan', 'Amravati', 'Maruthi mandir', 110048, 'NE India', 'JK vs Delhi');
INSERT into cric_players values(50, 'Nkrumah Bonner', 150, 500, 'Japan', ' Rangers', 'South Africa tour of West Indies, 2021', 'Lokesh', 'Bhagyashree', 'Suresh Gopi', 'Noida', 'Anjaneya nagar', 110049, 'Srilanka', 'BTM Vs Rajajinagar');

commit;

truncate cric_players;



