SELECT * FROM jan7batch.festivals;

CREATE TABLE festivals(id int, fest_name varchar(30), fest_date date, fest_day varchar(30), region varchar(30), specialFood varchar(30), VegSpecial varchar(30), NonVegSpecial varchar(30), fest_type varchar(30) );

alter table festivals add fest_noOfDays int;
alter table festivals add history varchar(60);
alter table festivals add celebrated_from year, add lastYearDate date, add lastYearDay varchar(30);

alter table festivals add spends bigint, add religion_followed varchar(30), add specialPerformances varchar(30);

alter table festivals add impact varchar(30);
alter table festivals add seasons varchar(30);
alter table festivals add worship varchar(30);

insert  into festivals values(1, 'RepublicDay', '2022-01-26', 'Thursday', 'Lucknow', 'Sweets', 'NA', 'NA', 'National Festival', 1, 'Constitution Adopted', '1950', '2022-01-26', 'Friday', 500, 'NA', 'Parides', 'Nationalism, Unity & Integrity', 'Winter', 'Bharathamathe');
insert  into festivals values(2, 'Sankranyhi', '2023-01-15', 'Saturday', 'Washington', 'Bella payasa', 'Obbattu', 'Chicken', 'Religious Festival', 2, 'to mark a new beginning', '0000', '2022-01-12', 'Monday', 5000, 'Hinduism', 'Family togetherness', 'Traditions followed', 'Winter', 'God Surya');
insert  into festivals values(3, 'Bohag Bihu', '2023-04-15', 'Saturday', 'Assam', 'K-Chira', 'Baanhgajor Lagot Kukura.', 'Duck Meat Curry.', 'Religious Festival', 10, 'coming of the New Year in the Assamese calendar', '0000', '2022-04-15', 'Tuesday', 0, 'Hinduism', 'Family togetherness', 'Traditions followed', 'Rainy', 'NA');
insert  into festivals values(4, 'Lohri', '2023-01-13', 'Friday', 'North India', 'Sarson Roti.', 'Pindi Channe.', ' Beseni Murgh', 'Punjabi folk festival', 2, 'celebration of winter solstice', '0000', '2022-01-13', 'Sunday', 0, 'Hinduism & Sikhism', 'Bonfire, song, and dance', 'Midwinter festival, ', 'Mid-winter', 'NA');
insert  into festivals values(5, 'Onam', '2023-01-18', 'Monday', 'Kerala', 'Palada payasam', 'Malabar Parotta', 'Karimeen pollichathu', 'Indian harvest festival', 2, 'commemorates Vamana', '0000', '2022-01-16', 'Friday', 50000, 'Keralites', 'remembrance of good governance', 'spectrum of cultural events, ', 'Mid-winter', 'Mahabali');
insert  into festivals values(6, 'Pongal', '2013-01-15', 'Wednesday', 'KempaNadu', 'Pongal', 'Puliyodarai', 'Chicken Chettinad', 'Harvest festiva', 7, 'Thai Pongal', '0000', '2022-01-15', 'Sunday', 0, 'Hinduism', 'home coming, prayers', 'Thanking the Sun God', 'Mid-winter', 'God Earth');
insert  into festivals values(7, 'Raksha Bandhan', '2023-08-30', 'Wednesday', 'Whole India', 'Chitranna', 'Puliyogari', 'Biriyani', 'Bonding', 1, 'Refresh', '1947', '2022-08-25', 'Monday', 50000, 'NA', 'Raki tieing', 'Thanking', 'NA', 'God Human');
insert  into festivals values(8, 'Dashehra', '2023-10-23', 'Saturday', 'London', 'Obbattu & Payasa', 'Kodbale', 'NA', 'victory of good', 1, 'Vijaya Dashmi', '0000', '2022-10-25', 'Monday', 10000, 'Hinduism', 'month of Ashvin', 'Navratri festivities', 'NA', 'God Human');
insert  into festivals values(9, 'Holi', '2023-03-08', 'Wednesday', 'Hampi', 'Finger Rice', 'Holige', 'Mutton Biriyani', 'divine love of Radha Krishna', 1, 'triumph of good over evil', '0000', '2022-03-25', 'Monday', 100, 'Hinduism', 'month of Ashvin', 'victory of Lord Vishnu', 'Summer', 'Krishna & Radha');
insert  into festivals values(10, 'Dipawali', '2023-11-12', 'Tuesday', 'Tumkur', 'Anna Food', 'Carrot Halwa & Holige', 'Chicken Biriyani', 'Festival of Lights', 3, ' Diya and lighting', '0000', '2022-11-05', 'Friday', 1000000, 'Hinduism', 'home decoration', 'puja and sweets', 'Summer', 'victory of light over darkness');
insert  into festivals values(11, 'IndependenceDay', '2023-08-15', 'Thursday', 'Jangama', 'Sweets', 'NA', 'NA', 'National Festival', 1, 'India got Independence', '1948', '2022-08-15', 'Friday', 1000, 'NA', 'Parides', 'Unity, Nationalism & Integrity', 'Summer', 'Bharathamathe');
insert  into festivals values(12, 'Id-ul Fitr', '2023-04-21', 'Friday', 'Kolkot', 'NA', 'NA', 'Special Mutton', 'end of dawn-to-sunset', 2, 'fasting of Ramadan', '0000', '2022-04-15', 'Tuesday', 0, 'Muslim', 'Eid prayers', 'Zakat al-Fitr charity', 'Summer', 'Eid al-Adha');
insert  into festivals values(13, 'Magh Bihu', '2003-01-15', 'Saturday', 'N-Assam', 'Doi-Chira', 'Baanhgajor Lagot Kukura.', 'Duck Meat Curry','Religious Festival', 5, 'related with agriculture', '0000', '2022-01-12', 'Thursday', 0, 'Hinduism', 'Family togetherness', 'Traditions followed', 'Winter', 'NA');
insert  into festivals values(14, 'Christmas', '2023-12-25', 'Monday', 'Europe', 'Cakes', 'IceCreams', 'kaima', 'religious fest', 7, 'exchange of gifts', '0000', '2022-12-25', 'Saturady', 0, 'singing of carols', 'Eid prayers', 'social gatherings', 'Winter', 'Jesus Christ');
insert  into festivals values(15, 'Nauroz', '2023-03-21', 'Thursday', 'Parts of India', 'Sabzeh', 'Samanu', 'Somaq', 'religious fest', 1, ' first month of Solar Hijri', '0000', '2022-03-21', 'Friday', 0, 'Parsians', 'feasting', 'visiting family members', 'Summer', ' Solar Hijri');
insert  into festivals values(16, 'Budddha Purnima', '2023-05-05', 'Friday', 'S-Karnataka', 'mixed rice', 'bibimbab', 'NA', 'religious fest', 1, ' birthday of Gautama Buddha', '0000', '2022-05-05', 'Friday', 0, 'Buddism', 'hanging of lanterns', 'enjoying communal meals', 'Summer', 'God Buddha');
insert  into festivals values(17, 'Ganeshotsava', '2023-09-19', 'Sunday', 'Bharat India', 'Kadubu anna', 'Payasa', 'NA', 'religious fest', 9, 'celebration of Lord Ganesha', '0000', '2022-08-31', 'Monday', 50000, 'Hinduism', 'Praying to Lord', 'Dances', 'Summer', 'God Ganesha');
insert  into festivals values(18, 'Navratri Durga Pooja', '2002-10-23', 'Saturday', 'Jaipur', 'Payasa & Kadubu', 'Special Kodbale', 'NA', 'victory of good', 9, 'Vijaya Dashmi', '0000', '2022-10-25', 'Monday', 10000, 'Hinduism', 'month of Ashvin', 'Navratri festivities', 'NA', 'God Human');
insert  into festivals values(19, 'Ambedkar Jayanthi', '2022-05-14', 'Thursday', 'Karna India', 'Sweets', 'NA', 'NA', 'National Festival', 1, 'Ambedkar birth ceremony', '1960', '2022-05-14', 'Friday', 0, 'NA', 'Praying', 'Nationalism, Unity & Integrity', 'Winter', 'Ambedkar');
insert  into festivals values(20, 'Ugadi', '2020-01-15', 'Saturday', 'Udaipur', 'Kadubu & PAYASA', 'Obbattu', 'Chicken', 'Religious Festival', 2, 'to mark a new beginning', '0000', '2022-01-12', 'Monday', 5000, 'Hinduism', 'New Year Day', 'family togetherness', 'Winter', 'Samvatsarādi');
insert  into festivals values(21, 'GandhiJayanthi', '2023-10-02', 'Thursday', 'Rama India', 'Sweets', 'NA', 'NA', 'National Festival', 1, 'Constitution Adopted', '1948', '2022-10-02', 'Friday', 0, 'NA', 'Parides', 'Unity, Integrity & Nationalism', 'Rainy', 'Mahatma Gandhi');
insert  into festivals values(23, 'Kati Bihu', '2023-10-15', 'Saturday', 'S-Assam', 'Doi-Chira', 'Baanhgajor Lagot Kukura.', 'Duck Meat Curry.','Religious Festival', 6, 'last day of the Ahin month of Assamese calendar', '0000', '2022-10-12', 'Sunday', 0, 'Hinduism', 'Family togetherness', 'Traditions followed', 'Summer', 'NA');
insert  into festivals values(22, 'Muharram', '2023-06-28', 'Friday', 'Krishna India', 'NA', 'NA', 'Camel special Mutton', 'religious fest', 30, 'Shia and Sunni Muslims', '0000', '2022-06-28', 'Tuesday', 0, 'Muslim', 'Eid prayers', 'social gatherings', 'Summer', 'Ashura');
insert  into festivals values(24, 'Good Friday', '2023-05-25', 'Monday', 'N-Europe', 'Sweets', 'Cakes', 'London Chicken', 'religious fest', 1, 'exchange of gifts', '0000', '2022-05-25', 'Saturady', 0, 'religious songs', 'jesus prayers', 'gifts & social gatherings', 'Summer', 'Jesus Christ');
insert  into festivals values(25, 'Kerala Onam', '2013-01-18', 'Monday', 'S-Kerala', 'Palada payasam', 'Malabar Parotta', 'Karimeen pollichathu', 'Indian harvest festival', 2, 'commemorates Vamana', '0000', '2022-01-16', 'Friday', 50000, 'Keralites', 'remembrance of good governance', 'spectrum of cultural events, ', 'Mid-winter', 'Mahabali');
insert  into festivals values(26, 'TamailNadu Pongal', '2008-01-15', 'Wednesday', 'IndiaNadu', 'Pongal', 'Puliyodarai', 'Chicken Chettinad', 'Harvest festiva', 7, 'Thai Pongal', '0000', '2022-01-15', 'Sunday', 0, 'Hinduism', 'home coming, prayers', 'Thanking the Sun God', 'Mid-winter', 'God Earth');
insert  into festivals values(27, 'Ganesh Chaturthi', '2023-03-22', 'Wednesday', 'Srilanadu', 'Kadubu', 'Yallakki payasa', 'Mutton', 'religious fest', 1, 'Samvatsarādi', '0000', '2022-03-20', 'Monday', 50000, 'Hinduism', 'New Year Day', 'family togetherness', 'Winter', 'Samvatsarādi');
insert  into festivals values(28, 'Karnataka Dashehra', '2015-10-23', 'Saturday', 'Huliyaru', 'Obbattu & Payasa', 'Kodbale', 'NA', 'victory of good', 1, 'Vijaya Dashmi', '0000', '2022-10-25', 'Monday', 10000, 'Hinduism', 'month of Ashvin', 'Navratri festivities', 'NA', 'God Human');
insert  into festivals values(29, 'Indian Holi', '2013-03-08', 'Wednesday', 'Gondsa', 'A Rice', 'Holige', 'Mutton Biriyani', 'divine love of Radha Krishna', 1, 'triumph of good over evil', '0000', '2022-03-25', 'Monday', 100, 'Hinduism', 'month of Ashvin', 'victory of Lord Vishnu', 'Summer', 'Krishna & Radha');
insert  into festivals values(30, 'Diwali', '2017-11-12', 'Tuesday', 'Tirupati', 'Anna Sambar', 'Carrot Halwa & Holige', 'Chicken Biriyani', 'Festival of Lights', 3, ' Diya and lighting', '0000', '2022-11-05', 'Friday', 1000000, 'Hinduism', 'home decoration', 'puja and sweets', 'Summer', 'victory of light over darkness');
insert  into festivals values(31, 'Independence Week', '2006-08-15', 'Thursday', 'Leela', 'Sweets', 'NA', 'NA', 'National Festival', 1, 'India got Independence', '1948', '2022-08-15', 'Friday', 1000, 'NA', 'Parides', 'Unity, Nationalism & Integrity', 'Summer', 'Bharathamathe');
insert  into festivals values(32, 'Special Id-ul Fitr', '2005-04-21', 'Friday', 'TN India', 'NA', 'NA', 'Special Mutton', 'end of dawn-to-sunset', 2, 'fasting of Ramadan', '0000', '2022-04-15', 'Tuesday', 0, 'Muslim', 'Eid prayers', 'Zakat al-Fitr charity', 'Summer', 'Eid al-Adha');
insert  into festivals values(33, 'Jellikattu', '2015-01-15', 'Wednesday', 'IndianaNadu', 'Pongal', 'Puliyodarai', 'Chicken Chettinad', 'Harvest festiva', 7, 'Thai Pongal', '0000', '2022-01-15', 'Sunday', 0, 'Hinduism', 'home coming, prayers', 'Thanking the Sun God', 'Mid-winter', 'God Earth');
insert  into festivals values(34, 'Easter', '2023-05-09', 'Sunday', 'S-Europe', 'Sweets', 'Cakes', 'London Chicken', 'religious fest', 1, ' Resurrection Sunday', '0000', '2022-05-25', 'Saturady', 0, 'Christian', 'resurrection of Jesus', 'Night vigil, sunrise service', 'Summer', 'Jesus Christ');
insert  into festivals values(35, 'Govardhan Pooja', '2013-11-12', 'Tuesday', 'N India', 'Mudde Sambar', 'Holige, Carrot Halwa', 'Chicken Biriyani', 'Festival of Lights', 3, ' Diya and lighting', '0000', '2022-11-05', 'Friday', 1000000, 'Hinduism', 'home decoration', 'puja and sweets', 'Summer', 'victory of light over darkness');
insert  into festivals values(36, 'Bogi Pongal', '2005-01-15', 'Wednesday', 'KingNadu', 'Pongal', 'Puliyodarai', 'Chicken Chettinad', 'Harvest festiva', 7, 'Thai Pongal', '0000', '2022-01-15', 'Sunday', 0, 'Hinduism', 'home coming, prayers', 'Thanking the Sun God', 'Mid-winter', 'God Earth');
insert  into festivals values(37, 'Jaisalmer Desert Festival', '2023-08-1', 'Wednesday', 'Rajasthan', 'rice', 'Sambar', 'Camel kaima', 'regional festival', 5, 'City heritage', '0000', '2022-08-1', 'Sunday', 0, 'NA', 'home coming', 'Thanking the god', 'Summer', 'NA');
insert  into festivals values(38, 'Kannada Rajyotsava', '2023-9-1', 'Sunday', 'Karnataka', 'Mudde', 'Sambar', 'Chicken Samabar', 'state festival', 1, 'State heritage', '1957', '2022-09-1', 'Tuesday', 0, 'NA', 'Kannada flag hoisting', 'Kannada ', 'Summer', 'Kannadambe');
insert  into festivals values(39, 'Kumbh Mela', '2023-5-15', 'Saturday', 'North-India', 'Special Payasa', 'Special Obbattu', 'Spec Chicken', 'Regional Festival', 4, ' to celebrate every revolutio', '2005', '2022-01-10', 'Monday', 5000, 'Hinduism', 'Family togetherness', 'Hindus celebration', 'Winter', 'God Kumba');
insert  into festivals values(40, 'Taj Mahotsav', '2023-9-15', 'Sunday', 'Agra', 'Special Laddu', 'Special Ladu', 'Special non veg', 'City Festival', 10, ' to celebrate everyone peace', '2000', '2022-05-10', 'Monday', 5000, 'Hinduism', 'road procession', 'inspired by old Mughal era', 'Winter', 'TajMahal');
insert  into festivals values(41, 'Pushkar Mela', '2016-9-01', 'Wednesday', 'Pushkar', 'Special camel sweets', 'Camel sweets', 'Special camel', 'City Festival', 5, 'to celebrate city peace', '2009', '2022-3-10', 'Sunday', 5000, 'NA', 'Dancing', 'multi-day livestock fair', 'Winter', 'Pushkar');
insert  into festivals values(42, 'Mango Festivals', '2023-05-1', 'Wednesday', 'Delhi', 'Chapathi', 'chetni', 'Chapati kaima', 'regional festival', 5, 'City heritage', '0000', '2022-05-1', 'Sunday', 0, 'NA', 'celebrating the city', 'Thanking the god', 'Summer', 'NA');
insert  into festivals values(43, 'GOOD DAY', '2016-05-25', 'Monday', 'Mid-Europe', 'Sweets', 'Cakes', 'London Chicken', 'religious fest', 1, 'exchange of gifts', '0000', '2022-05-25', 'Saturady', 0, 'religious songs', 'jesus prayers', 'gifts & social gatherings', 'Summer', 'Jesus Christ');
insert  into festivals values(44, 'Chaitra Navratri', '2020-05-15', 'Saturday', 'Fazihabad', 'Kai payasa', 'Obbattu', 'Chicken', 'Religious Festival', 2, 'to mark a new beginning', '0000', '2022-01-12', 'Monday', 5000, 'Hinduism', 'New Year Day', 'family togetherness', 'Winter', 'Samvatsarādi');
insert  into festivals values(45, 'Childrens day', '2022-05-14', 'Thursday', 'KrishnanNadu', 'Sweets', 'NA', 'NA', 'National Festival', 1, 'Ambedkar birth ceremony', '1960', '2022-05-14', 'Friday', 0, 'NA', 'Praying', 'Nationalism, Unity & Integrity', 'Winter', 'Ambedkar');
insert  into festivals values(46, 'Parents day', '2022-09-14', 'Thurs', 'India', 'Indian Sweets', 'NA', 'NA', 'Family Festival', 365, 'facilatate our respects', '2000', '2022-09-14', 'Fri', 0, 'NA', 'Praying for family', 'Respecting the society', 'Every day', 'Father');
insert  into festivals values(47, 'Garden Festival', '2016-08-1', 'Wednesday', 'Sikkim', 'Rotti', 'Chetni', 'Sheep kaima', 'regional festival', 5, 'City heritage', '0000', '2022-08-1', 'Sunday', 0, 'NA', 'home coming', 'Thanking the god', 'Summer', 'NA');
insert  into festivals values(48, 'Whatsapp Festival', '2023-01-1', 'Wed', 'All', 'Pizz', 'Burger', 'KFC', 'social media festival', 360, 'social connectivity', '2016', '2022-8-1', 'Sun', 0, 'NA', 'Chating', 'Video calling', 'whole year', 'Connnecting');
insert  into festivals values(49, 'Facebook Festival', '2000-01-1', 'Wedn', 'Indians', 'Pizza', 'Blr Burger', 'FC KFC', 'social festival', 365, 'social media', '2014', '2022-8-8', 'Fri', 0, 'NA', 'Stories', 'Posts', 'whole decade', 'Connnecting world');
insert  into festivals values(50, 'Elephant Festival', '2023-02-1', 'Monday', 'S-Kerala', 'Idli', 'Palya', 'Special Kaima', 'regional festival', 5, 'City heritage', '0000', '2022-02-1', 'Sunday', 0, 'NA', 'home coming', 'Thanking the god', 'Summer', 'NA');




truncate festivals;